"""L4 — migrations: upgrade creates the schema; full up/down/up cycle works."""

from __future__ import annotations

import sqlite3
from pathlib import Path

from alembic import command

from kvseo.storage.db import _alembic_config, migrate

EXPECTED_TABLES = {
    "clients",
    "sites",
    "audit_runs",
    "audit_checks",
    "advisor_outputs",
    "gsc_queries",
    "psi_results",
    "reports",
    "schema_meta",
}


def _tables(db: Path) -> set[str]:
    conn = sqlite3.connect(db)
    try:
        rows = conn.execute("SELECT name FROM sqlite_master WHERE type='table'")
        return {r[0] for r in rows}
    finally:
        conn.close()


def test_migrate_creates_all_tables(tmp_path: Path) -> None:
    db = tmp_path / "kvseo.db"
    migrate(db)
    tables = _tables(db)
    assert tables >= EXPECTED_TABLES
    assert "alembic_version" in tables


def test_migrate_sets_wal(tmp_path: Path) -> None:
    db = tmp_path / "kvseo.db"
    migrate(db)
    conn = sqlite3.connect(db)
    try:
        mode = conn.execute("PRAGMA journal_mode").fetchone()[0]
    finally:
        conn.close()
    assert mode.lower() == "wal"


def test_migrate_is_idempotent(tmp_path: Path) -> None:
    db = tmp_path / "kvseo.db"
    migrate(db)
    migrate(db)  # second run must not error
    assert _tables(db) >= EXPECTED_TABLES


def test_full_upgrade_downgrade_cycle(tmp_path: Path) -> None:
    db = tmp_path / "kvseo.db"
    cfg = _alembic_config(db)
    command.upgrade(cfg, "head")
    assert _tables(db) >= EXPECTED_TABLES
    command.downgrade(cfg, "base")
    assert not (EXPECTED_TABLES & _tables(db))  # all domain tables dropped
    command.upgrade(cfg, "head")  # re-upgrade is clean
    assert _tables(db) >= EXPECTED_TABLES


def test_models_match_migrations(tmp_path: Path) -> None:
    """Drift guard: a model change without a matching migration fails here.

    `alembic check` raises AutogenerateDiffsDetected if the ORM metadata and the
    migrated schema diverge.
    """
    db = tmp_path / "kvseo.db"
    cfg = _alembic_config(db)
    command.upgrade(cfg, "head")
    command.check(cfg)  # raises if models and migrations disagree
