"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-06-23 08:39:31.762181
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.LargeBinary(length=16), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('gsc_queries',
    sa.Column('id', sa.LargeBinary(length=16), nullable=False),
    sa.Column('site_origin', sa.String(), nullable=False),
    sa.Column('page', sa.Text(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('range_start', sa.String(), nullable=False),
    sa.Column('range_end', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gsc_queries', schema=None) as batch_op:
        batch_op.create_index('idx_gsc_page_query', ['page', 'query', 'range_end'], unique=False)
        batch_op.create_index('idx_gsc_site_time', ['site_origin', 'fetched_at'], unique=False)

    op.create_table('psi_results',
    sa.Column('id', sa.LargeBinary(length=16), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('field_lcp_ms', sa.Integer(), nullable=True),
    sa.Column('field_inp_ms', sa.Integer(), nullable=True),
    sa.Column('field_cls', sa.Float(), nullable=True),
    sa.Column('field_origin_fallback', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('lab_lcp_ms', sa.Integer(), nullable=False),
    sa.Column('lab_tbt_ms', sa.Integer(), nullable=False),
    sa.Column('lab_cls', sa.Float(), nullable=False),
    sa.Column('lab_performance_score', sa.Integer(), nullable=False),
    sa.Column('opportunities', sa.JSON(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('psi_results', schema=None) as batch_op:
        batch_op.create_index('idx_psi_url_time', ['url', 'strategy', 'fetched_at'], unique=False)

    op.create_table('schema_meta',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('sites',
    sa.Column('id', sa.LargeBinary(length=16), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('client_id', sa.LargeBinary(length=16), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origin')
    )
    op.create_table('audit_runs',
    sa.Column('id', sa.LargeBinary(length=16), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('fetched_url', sa.Text(), nullable=True),
    sa.Column('keyword', sa.String(), nullable=True),
    sa.Column('site_id', sa.LargeBinary(length=16), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'running'"), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('page_title', sa.Text(), nullable=True),
    sa.Column('page_status_code', sa.Integer(), nullable=True),
    sa.Column('fetch_duration_ms', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('strategy', sa.String(), server_default=sa.text("'mobile'"), nullable=False),
    sa.Column('fetched_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'complete', 'failed')", name='ck_audit_runs_status'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_runs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_runs_site_time', ['site_id', 'fetched_at'], unique=False)
        batch_op.create_index('idx_audit_runs_status', ['status'], unique=False, sqlite_where=sa.text("status != 'complete'"))
        batch_op.create_index('idx_audit_runs_url_time', ['url', 'fetched_at'], unique=False)

    op.create_table('advisor_outputs',
    sa.Column('id', sa.LargeBinary(length=16), nullable=False),
    sa.Column('audit_run_id', sa.LargeBinary(length=16), nullable=False),
    sa.Column('prompt_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.CheckConstraint("status IN ('success', 'invalid_output', 'failed')", name='ck_advisor_outputs_status'),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advisor_outputs', schema=None) as batch_op:
        batch_op.create_index('idx_advisor_outputs_audit', ['audit_run_id', 'prompt_id'], unique=False)
        batch_op.create_index('idx_advisor_outputs_cost', ['created_at'], unique=False)

    op.create_table('audit_checks',
    sa.Column('id', sa.LargeBinary(length=16), nullable=False),
    sa.Column('audit_run_id', sa.LargeBinary(length=16), nullable=False),
    sa.Column('check_id', sa.String(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.CheckConstraint("severity IN ('info', 'warn', 'fail')", name='ck_audit_checks_severity'),
    sa.CheckConstraint("verdict IN ('pass', 'warn', 'fail', 'skip', 'error')", name='ck_audit_checks_verdict'),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_checks', schema=None) as batch_op:
        batch_op.create_index('idx_audit_checks_check', ['check_id', 'verdict'], unique=False)
        batch_op.create_index('idx_audit_checks_run', ['audit_run_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.LargeBinary(length=16), nullable=False),
    sa.Column('site_id', sa.LargeBinary(length=16), nullable=True),
    sa.Column('client_id', sa.LargeBinary(length=16), nullable=True),
    sa.Column('range_start', sa.String(), nullable=False),
    sa.Column('range_end', sa.String(), nullable=False),
    sa.Column('template', sa.String(), server_default=sa.text("'monthly'"), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('narrative_id', sa.LargeBinary(length=16), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['narrative_id'], ['advisor_outputs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index('idx_reports_site_time', ['site_id', 'range_end'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index('idx_reports_site_time')

    op.drop_table('reports')
    with op.batch_alter_table('audit_checks', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_checks_run')
        batch_op.drop_index('idx_audit_checks_check')

    op.drop_table('audit_checks')
    with op.batch_alter_table('advisor_outputs', schema=None) as batch_op:
        batch_op.drop_index('idx_advisor_outputs_cost')
        batch_op.drop_index('idx_advisor_outputs_audit')

    op.drop_table('advisor_outputs')
    with op.batch_alter_table('audit_runs', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_runs_url_time')
        batch_op.drop_index('idx_audit_runs_status', sqlite_where=sa.text("status != 'complete'"))
        batch_op.drop_index('idx_audit_runs_site_time')

    op.drop_table('audit_runs')
    op.drop_table('sites')
    op.drop_table('schema_meta')
    with op.batch_alter_table('psi_results', schema=None) as batch_op:
        batch_op.drop_index('idx_psi_url_time')

    op.drop_table('psi_results')
    with op.batch_alter_table('gsc_queries', schema=None) as batch_op:
        batch_op.drop_index('idx_gsc_site_time')
        batch_op.drop_index('idx_gsc_page_query')

    op.drop_table('gsc_queries')
    op.drop_table('clients')
    # ### end Alembic commands ###
